server:
  port: 9091
  error:
    include-message: always

spring:
  application:
    name: rental-car-api
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/